when:
    - event: push
      branch: host

steps:
    - name: build
      image: docker:24
      commands:
          # Build the Docker image from your Dockerfile
          - docker build -t chiral-network:latest -f Dockerfile .
